#:schema node_modules/wrangler/config-schema.json
name = "workers-ai-image-playground"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = "ai-img-playground"
binding = "BUCKET"

[vars]
CLOUDFLARE_ACCOUNT_ID = "58b1b19c68acaef9ec1347796c8ef5dc"
CLOUDFLARE_API_TOKEN = "gogO1poYuaXgoJkS3dVaWz4FHLtC48smqsZ_0s2R"
